# Generated by Django 3.2 on 2023-02-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('profile_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Users_Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('started_following', models.DateTimeField(auto_now_add=True)),
                ('following_user_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('poster_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('commenter_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.users')),
                ('post', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.post')),
            ],
        ),
    ]
