# Generated by Django 3.2 on 2023-02-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0005_auto_20230228_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('liker_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.users')),
                ('post', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.post')),
            ],
        ),
    ]
