# Generated by Django 3.2 on 2023-03-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0006_auto_20230228_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_imgs'),
        ),
    ]
