# Generated by Django 3.2 on 2023-03-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0008_chat_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='room_name',
            new_name='name',
        ),
    ]
