# Generated by Django 3.2 on 2023-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0010_alter_chat_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
