# Generated by Django 3.2 on 2023-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0012_alter_users_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_loggin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
