# Generated by Django 3.2 on 2023-03-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0013_users_last_loggin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_following',
            name='following_user_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='Finals_app.users'),
        ),
    ]
