# Generated by Django 3.2 on 2023-03-12 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finals_app', '0014_alter_users_following_following_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_imgs', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
